[GLOBAL]
pants_version = "2.16.0"
backend_packages.add = [
    "pants.backend.docker",
    "pants.backend.docker.lint.hadolint",
    "pants.backend.build_files.fmt.black",
    "pants.backend.python",
    "pants.backend.python.lint.docformatter",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.flake8",
]
colors = true

[python]
interpreter_constraints = ["==3.9.*"]

enable_resolves = true
resolves = { python-default = "python-default.lock" }

